---
title: "gij bent 2"
author:
  - name: Anthe Sevenants
    email: anthe.sevenants@kuleuven.be
    orcid: 0000-0002-5055-770X
    affiliations:
      - name: KU Leuven
  - name: Julie Nijs
    email: julie.nijs@kuleuven.be
    orcid: 000-0002-7421-9887
    affiliations:
      - name: KU Leuven
format:
  html:
    toc: true
  docx:
    toc: false
editor: source
title-block-banner: true
bibliography: references.bib
toc: true
toc-depth: 4
toc-location: left
tbl-cap-location: bottom
fig-cap-location: bottom
number-sections: true
reference-location: margin
csl: chicago-author-date.csl
df-print: kable
abstract: |
  TODO
execute:
  echo: false
---

```{r initialisation}
#| output: false
library(scales)

formatn <- function(number) {
    format(round(as.numeric(number), 1), nsmall=0, big.mark=",")
}

formatd <- function(number, nsmall=2) {
    format(round(number, nsmall), nsmall=nsmall)
}

formatp <- function(number) {
    label_percent()(number)
}

suppress_gloss <- FALSE
```

## Introduction {#sec:introduction}

One of the key ideas from usage-based linguistics is that language is not a system that exists just "by itself". Rather, it is widely accepted within this branch that language arises out of the many interactions that language users have with each other [TODO source]. As such, language becomes a "complex-adaptive system" [TODO source], a system without a single authoritative control, constructed through the simple yet numerous interactions of its components, language users. While each speaker of a language (be it Dutch, English or Maori) has their own personalised representation of the rules and constraints that they think make up that language, these representations have enough in common in order to warrant talking about a shared "code", or more broadly, a language.

When it comes to research of said shared code, things become more complicated. It is impossible for researchers to know the complete code of *all* language users in a language system. This situation forces models of language into necessary generalisations. Generalisation is a valid strategy, as most linguistic variation, when tallied at large, will lead to a Zipfian A-curve [as suggested by Kretzschmar, TODO]. The make-up of this curve, with the most popular forms capturing most of the language use anyway, make it so the "general" behaviour of language variation that is typically captured in corpora also represents a fair share of what would be the individual code of most language users. Of course, there are factors influencing what language forms are used,[^lects] but broadly speaking, this generalisation holds. We see this, for example, in probabilistic grammar, [todo definition]. Still, on a theoretical level, it is regrettable that models of variation do not start from the lowest common denominator of this variation: the language user.

[^lects]: i.e. "lects", TODO Geeraerts

Contrastively, the advent of social media offers a unique opportunity for variationist research. Social media platforms offer an insight into the language systems of a large number of people.  Whereas previously it was possible to gauge the linguistic profile of only a small group of people [e.g. Milroy, Labov], social media offer linguistic variation at an unprecedented scale.[^c-clamp] While one should not consider spoken and written social media as equivalent, social media language has nonetheless proven a useful proxy for the former [TODO source]. In addition, social media data of course do not provide access to *all* of language for *all* users of a language system; not all utterances are made on social media, nor are all language users active on social media platforms. Nevertheless, social media platforms bring us closer to the idea of studying language *inside out*, starting from individual language users' variation, even if it is only for a single alternation among a subset of language users. This brings us to the first research question of this study:

1. What affordances does a focus on individual variation bring us in the context of alternation research, especially in contrast to traditional, aggregated alternation research?

[^c-clamp]: More recently, the release of the C-Clamp corpus [todo] offers a diachronic insight into the language use of Dutch-speaking writers from XXX to XXX. The historical nature of this corpus, however, limits its use for research into contemporary language variation phenomena.

Another aspect of of the complex-adaptive system of language are the connections between people. Humans are embedded in larger social networks, which are formed according to a so-called "power law". [uitleg scale-free netwerk]
Linguistically, the effects of networks has been studied before [stuk Julie].

- leaders / loaners
- gedrag van centrale figuren
- alle andere dingen die interessant zouden kunenn zijn

Except for small-scale studies [e.g. Milroy & Labov TODO], it has been impossible to get an elaborate insight into the social relationships of people on a large scale, let alone how these relationships relate to language. Again, social media offer an opportunity here. While it is not practical to get a full network of *all* social media users, we *can* get information on how "connected" a particular user is. Through metrics like "followers" and "following", we know how many connections social media users have. This allows us to get an idea of the centrality of a user in the larger social media network, even if we do not know the full network itself. This brings us to the second research question in this study:

2. How can we leverage the implicit network inherent in social media data to learn more about the spread of linguistic innovations?

To answer the two research questions stated above, we follow up on a study by Sevenants [TODO] about *gij bent*, a linguistic innovation concerning the second person of 'to be' in Colloquial Belgian Dutch (CBD). To compute the individual variation of different language users, we will use elastic net regression, a regression analysis technique pioneered in [todo]. First, we will introduce the *gij bent* CBD linguistic innovation. Then, we will describe how we modelled the linguistic profiles of the individual user with regard to this innovation using elastic net, and why we need this specific technique to answer the questions we have in this study. Next, we will show the results of our analyses, and discuss what consequences they have for usage-based alternation research in general.

## The case of *gij bent*

This study focusses on *gij bent*, an innovation within Colloquial Belgian Dutch (CBD). Before we explain what this innovation is about, we will first explain the general language situation of Dutch in Belgium.

### Dutch in Belgium

Dutch as it is spoken in Belgium has evolved strongly since the second half of the 20^th century. Until deep in the 20^th century, the language situation of Dutch in  Flanders, the Dutch-speaking part of Belgium, could best be described as a *diglossia* [Auer 2005 TODO]. This means that the Dutch was characterised by a dichotomy between standard language on the one hand, and dialects on the other hand. These two were the language modes available to speakers of Dutch. From the XXXies TODO onwards, a large-scale language policy campaign attempted to teach those speakers who mastered only their local dialect the standard language. While these efforts were well intended, the imposition of a "foreign" standard language -- the standard was imported from the Netherlands -- were met with limited enthusiasm by language users in Flanders. However, this language campaign was not without effect, albeit not the intended one.

At the start of the 21^st century, it had become clear that Flanders was evolving into a new type of language situation: *diaglossia* [again Auer 2005]. In between the dialects and standard language, new language types had appeared, among which so-called "regiolects" (above the dialects) and "regional standards" (below standard language). More generally, however, a new term was coined: *tussentaal*, which roughly translates to "interlanguage". In this article, we will use the term defined by TODO, "Colloquial Belgian Dutch" or CBD.

The new variant CBD is characterised by being hard to define. In general, it is best described as a "standard-adjacent", colloquial form of Belgian Standard Dutch, with both general Flemish elements and region-specific features added to it on all levels (phonology, morphology, syntax etc.). The presence of region-specific features means that CBD is not a monolithic language variety, but rather sounds different across all places in Flanders. This inherent variability is intrinsic to its linguistic identity, but frustrating to linguists, who have been trying to come up with "defining features" for decades [todo citaties Zenner].

### *gij bent*

Traditionally in Flanders, if one wishes to say "you are" in an informal way, they would say *gij zijt*. *Gij* marks the informal second person pronoun that is typical to most Flemish dialects. *Zijt* is a historic form of *zijn* 'to be' that is now exclusively used with this pronoun. If one wanted to say "you are" in a formal way (i.e. in standard language), they would say *jij bent*. *Jij* marks the non-polite, yet formal second person pronoun in Flanders. *Jij* is more formal than *gij* because the *jij* pronoun is actually a Netherlandic form that, because it is foreign, has a different status than *gij*. *Bent* is the conjugated form that goes along with *jij*. It is also imported from the Netherlands.

It is clear, then, that these two forms are distinctly different from each other. However, in CBD, a blend of these two forms has appeared: *gij bent*. It combines the *gij* pronoun from *gij zijt* with the *bent* conjugation known from standard language. *Gij bent* is a quite literal example of the diaglossia situation, as it combines *gij* and *bent* from polar opposites of the language spectrum and meets somewhere in the middle.

Research by [mezelf lol TODO] has shown that *gij bent* most likely originated in dialects from the northern Antwerp province in Flanders, and then spread to other parts of the Brabantian dialect area.[^brabants] The reason for the spread from this area is argued to lie in the function of *gij bent*. The *jij bent* from standard language might feel too formal, while the *gij zijt* from dialects might feel too blunt. *Gij bent* strikes a balance between the two: it has colloquial roots through Flemish *gij*, but benefits from the prestige associated with standard language [todo referentie] through standard *bent*. In addition, both regional, formality and gender effects were found:

1. the use of *gij bent* is limited to the Brabant dialect region only
2. the use of *gij bent* is less likely in more informal contexts
3. the use of *gij bent* is more likely for women

[^brabants]: Brabants is the dialect area coinciding, mostly, with the Flemish provinces "Vlaams-Brabant" and "Antwerp". It is said to be the driving force behind CBD, but this claim is disputed [todo Lybaert reference].

While these conclusions are drawn from language use originating from social media, the analysis itself is very traditional. As in a standard corpus linguistic study, it generalises over all language at once, as well as all language users. This leads to blanket statements as the ones above. As argued before, there is nothing inherently wrong with this approach, but given the opportunities in social media data, a more bottom-up approach would be interesting. More specifically, such an approach would allow us to detect whether certain language users behave differently from what we would expect given their location or gender. These deviations from general expectations are now invisible in the generalising models. In addition, no account was taken of the network structure hidden in the data, which might reveal more about the forces and the direction this innovation will take in the future.

### Elastic net regression